#!/bin/sh

# 1. Create mount points and mount essential filesystems (Required for both kernels)
mkdir -p /proc /sys /dev
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo "[*] Loading kexec module..." > /dev/kmsg
/bin/finit_loader /lib/kexec_mod.ko > /dev/kmsg 2>&1

echo "[*] Waiting for device node..." > /dev/kmsg
# Give devtmpfs a moment to populate the /dev directory
while [ ! -e /dev/custom_kexec ]; do
    sleep 0.1
done

echo "[*] Triggering pivot..." > /dev/kmsg
# /bin/custom_kexec
