#!/bin/sh

# 1. Mount essential filesystems
mkdir -p /proc /sys /dev /dev/pts
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev 2>/dev/null || true
mount -t devpts none /dev/pts 2>/dev/null || true

# 2. Route all script output to the kernel log
exec >/dev/kmsg 2>&1

echo "===================================================="
echo "   [CCD SERIAL BOOT] FINAL TARGET KERNEL REACHED    "
echo "===================================================="
echo "[*] Essential filesystems mounted successfully."

# 3. Setup Environment
export PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export HOME="/"
export TERM="linux"
export PS1="Final-Serial# "

if [ "$board_id" = "grunt" ]; then
    echo "[*] DIAGNOSTICS: Forcing ttyS0 hardware map via setserial"
    setserial /dev/ttyS0 uart 16550A port 0 irq 0 iomem_base 0xfedc6000 iomem_reg_shift 2 baud_base 3000000
fi

cat /proc/tty/driver/serial


echo "[*] Launching getty on the active console..."

# 4. Launch the shell using GETTY
# Note: We pass 'console' without the /dev/ prefix.
while true; do
    setsid getty -L -n -l /bin/sh 115200 /dev/ttyS0 vt100

    echo "[-] FATAL: getty exited or crashed. Restarting in 1 second..."
    sleep 1
done
